trigger:
  - main

# Use your self-hosted agent named JASHRUTHA
pool:
  name: JASHRUTHA  # Use your self-hosted agent's pool name

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python add.py
    displayName: 'Run Python Script'
